---
- name: Ensure that there there are no other network managing daemons.
  systemd_service:
    name: "{{ item }}"
    state: stopped
    enabled: false
  loop:
    - NetworkManager
    - wpa_supplicant
    - systemd-networkd

- name: Configuring network interfaces.
  template:
    src: "interface.j2"
    dest: "/etc/network/interfaces.d/{{ item.interface }}"
    owner: root
    group: root
    mode: u=rw,g=r,o=
  with_items: "{{ network_interfaces }}"
  notify:
    - Restart networking
